id = "s-darktheme"
name = "S-Dark Theme"
version = "1.0.0"
authors = ["Sina Mombeiny <SMombeiny@proton.me>"]
description = "A beautiful dark theme."
repository = "https://github.com/sinamombeiny/S-DarkTheme.zed"
