on:
  push:
    tags:
      - "v*"

jobs:
  bump-zed-extension:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: s-dark-theme
          push-to: SinaMombeiny/zed.extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
